== Other informative information about the work of this SWG

=== Collaboration

SWG cooperation will aim at standards formulation in the shared working space, identification and division of tasks, solving arised issues accordingly to their urgency and severity, tracing the progress and planning.

The AIM SWG will use for collaboration:
 * Github repository with the standard document and formal model
 * Github issue tracker for outstanding tasks and considerations as well as change requests
 * slack channel
 * bi-weekly telcos for ongoing work and issues discussion


=== Similar or Applicable Standards Work (OGC and Elsewhere)

Deliverable D2.3 of the H2020 DEMETER project (https://nc.h2020-demeter.eu/index.php/s/RggDtq76zkXD84n) elaborates the alignments and relations with different models including: INSPIRE/FOODIE, FIWARE AgriFood dta models, SAREF4AGRI, ADAPT, FOODON, AGROVOC, EPPO, and other OGC Earth Observation standards.
D2.3 includes the analysis of other relevant models, describing their potential incorporation in AIM, e.g., Crop ontology, ISOBUS, GS1, and AFarCloud. Deliverable D2.5 of DEMETER that is planned for delivery in April 2023 will present in detail the latest version of AIM along with all recent extensions.

==== W3C/OGC Spatial Data on the Web Interest Group

(And/or its successor, the Spatial Data on the Web Working Group)

===== Scope of Activity

This group operates within the W3C as well as the OGC in order to develop and maintain vocabularies and best practices that encourage better sharing of spatial data on the Web; and identify areas where standards should be developed jointly by both W3C and the Open Geospatial Consortium (OGC). It allows members of both organizations to collaborate in the creation of standards an best practices related to both Web and spatial data.

The group is expected to be transformed into a working group over the course of the year 2020.

===== Web Site(s)

https://www.w3.org/2017/sdwig/

===== Source Repositories

https://github.com/w3c/sdw

===== Liaisons

 - Linda van den Brink
 - Joseph Abhayaratna


==== RDA IGAD

===== Scope of Activity

Improving Global Agricultural Data (IGAD) Community of Practice, formerly called The Interest Group on Agricultural Data (IGAD), is building practices of interoperability for research data for agriculture.
The Group has published several Best Practices for specific subdomains and semantics in general.
Cooperation will help to work out common practice on semantics in the agriculture.

===== Web Site(s)

 -  https://www.rd-alliance.org/groups/agriculture-data-interest-group-igad.html

===== Liaisons

 - Cynthia Sims Parr
 - Karel Charvat

==== Saref4Agri/FIWARE

===== Scope of Activity

This group is working on the ETSI standards supported in the AIM and supported in important data-spaces related initiatives namely NGSI-LD and Saref4Agri.
Liaison will work on the models alignment and potential representation practices in selected encodings.

===== Web Site(s)

 - https://ngsi-ld-tutorials.readthedocs.io/en/latest/

===== Source Repositories

 - https://github.com/fiware/tutorials.NGSI-LD

===== Liaisons

Juanjose Hierro



=== Other Related Work

This proposed SWG is to enhance an existing OGC standard - an ontology - however the Best Practices for ontology publication have changed since the original GeoSPARQL publication. The ontology publication methods of other standards bodies, particularly the W3C who continuously generates new standard ontologies, will be considered to determine appropriate, Best Practice, ontology publication.

This may include the use of tools to automatically generate human-readable ontology versions from the technical ontology artifact, such as those used by inputs to this work, for example the http://linked.data.gov.au/def/geox[GeoSPARQL Extensions Ontology].

In case of profiles definition *profile* as well as an ontology, in line with recent work by OGC members and others to establish standard ways of indicating the dependencies between standards, as per https://www.w3.org/TR/dx-prof/[The Profiles Vocabulary].

RDA IGAD Agrisemantics WG report ‘39 Hints to Facilitate the Use of Semantics for Data on Agriculture and Nutrition’ doi.org/10.15497/RDA00036


=== Details of first meeting

The first meeting of the SWG will be held by telephone conference call within 2 weeks following the week of Technical Committee approval of this Charter. Call-in information will be provided to the SWG’s e-mail list and on the portal calendar in advance of the meeting.

=== Projected on-going meeting schedule

The work of the SWG will be carried out primarily by email and conference calls, possibly every two weeks, with face-to-face meetings perhaps at each of the OGC TC meetings.

=== Supporters of this Charter

The following people support this proposal and are committed to the Charter and projected meeting schedule. These members are known as SWG Founding or Charter members. The charter members agree to the SoW and IPR terms as defined in this charter. The charter members have voting rights beginning the day the SWG is officially formed. Charter Members are shown on the public SWG page.

|===
|Name |Organization
|K. Charvat | Plan4All
|R. Palma | PSNC
|I. Roussaki | NTUA
|I. Roussaki | ICCS
|R. Atkinson, P. Zaborowski | OGC COSI
|===

=== Conveners

|===
|Name |Organization
|I. Roussaki | ICCS
|R. Palma | PSNC
|K. Charvat | Plan4All
|===
